# alias
alias mk=mkdir
alias cls=clear
# alias ls='exa'
# alias la='exa -a'
# alias ll='exa -l'
alias ls='lsd'
alias la='lsd -a'
alias ll='lsd -l'
#alias ls='ls --color=auto'
# alias la='ls -a --color=auto'
# alias ll='ls -l --color=auto'
alias sup='sudo apt update'
alias sug='sudo apt upgrade'
alias ssa='apt search'
alias ssz='zypper se'
alias zup='sudo zypper up'
alias zdg='sudo zypper dup'
alias oup='opam update'
alias oug='opam upgrade'
alias bup='brew2 update'
alias bug='brew2 upgrade'
alias bcls='brew2 cleanup'
alias fdsize='du -h --max-depth=1'
# alias wget='wget2'
