# Inserts a blank line between shell prompts
add_newline = false
command_timeout = 1000

[directory]
truncation_length = 0
truncate_to_repo = false
# fish_style_pwd_dir_length = 1
#style = "bold cyan"
style = "#8178a7"
# format = "[$path]($style)[$read_only]($read_only_style)"

[git_branch]
format = "[$branch]($style) "

[cmd_duration]
format = "[$duration]($style) "
min_time = 3_000

[character]
# success_symbol = "[➜](bold green)"
success_symbol = "[λ](bold black)"
error_symbol = "[✘](bold red)"
vicmd_symbol = "[V](bold blue) "


[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[$user@]($style)"
disabled = false

[hostname]
ssh_only = true
format =  "[$hostname](bold yellow) "
disabled = false

[git_status]
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked\]]($style))'
conflicted = '!'

[package]
disabled = true

[dotnet]
disabled = true
